--STATUS

CREATE TABLE public."Status" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,
	CONSTRAINT "PK_Status" PRIMARY KEY ("id")
);

INSERT INTO public."Status" ("name") VALUES('Leve');
INSERT INTO public."Status" ("name") VALUES('Moderado');
INSERT INTO public."Status" ("name") VALUES('Grave');
INSERT INTO public."Status" ("name") VALUES('Gravíssimo');

--FLOW
CREATE TABLE public."Flow" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,
	CONSTRAINT "PK_Flow" PRIMARY KEY ("id")
);

INSERT INTO public."Flow" ("name") VALUES('Chegada');
INSERT INTO public."Flow" ("name") VALUES('Inicializada');
INSERT INTO public."Flow" ("name") VALUES('Finalizada');
INSERT INTO public."Flow" ("name") VALUES('Interrompida');

--PATIENT

CREATE TABLE public."Patient" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,
    "status_id" int4 NOT NULL,        
	CONSTRAINT "PK_Patient" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Patient_Status_Id" FOREIGN KEY ("status_id") REFERENCES public."Status"("id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Patient_Status_Id" ON public."Patient" USING btree ("status_id");

--TREATMENT
CREATE TABLE public."Treatment" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"patient_id" int4 NOT NULL,
	"flow_id" int4 NOT NULL,
	"day" int4 NOT NULL,
	"time" real NOT NULL,
	"time_spent" real NOT NULL,
	CONSTRAINT "PK_Treatment" PRIMARY KEY ("id"),
	CONSTRAINT "FK_Treatment_Patient_Id" FOREIGN KEY ("patient_id") REFERENCES public."Patient"("id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Treatment_Flow_Id" FOREIGN KEY ("flow_id") REFERENCES public."Flow"("id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Treatment_Patient_Id" ON public."Treatment" USING btree ("patient_id");
CREATE INDEX "IX_Treatment_Flow_Id" ON public."Treatment" USING btree ("flow_id");

--DOCTOR
CREATE TABLE public."Doctor" (
	"id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
	"name" varchar(50) NOT NULL,
    "patient_id" int4 NOT NULL, 
	"time" real NOT NULL,       
	CONSTRAINT "PK_Doctor" PRIMARY KEY ("id"),
    CONSTRAINT "FK_Doctor_Patient_Id" FOREIGN KEY ("patient_id") REFERENCES public."Patient"("id") ON DELETE RESTRICT
);